# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: analyticschallenge
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  job:
    build: .
    volumes:
      - type: bind
        source: ./moviearchive
        target: /moviearchive
    environment:
      MYSQL_URL: "analytics-engineer-challenge_db_1"
      MYSQL_PORT: "3306"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "example"
      MYSQL_DATABASE: "analyticschallenge"
      MOVIE_DATA_PATH: "/moviearchive"
